name: Deploy MkDocs site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run:
          pip install mkdocs mkdocs-material

      - name: Build MkDocs site
        run:
          mkdocs build
      

      - name: Check for symlinks #Check for symlinks
        run: find . -type l -exec ls -l {} \;

      - name: Debug List generated files #ebug step to check if MkDocs actually created the site/ directory:
        run: ls -R site/
      

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload Pages artifact #Upload Pages artifact org
        uses: actions/upload-artifact@v4.6.1
        with:
          name: github-pages # must match what the deploy step expects
          path: ./site  # ./site orig Replace with your actual build directory

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4